name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run test
        run: deno test
