name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run test
        run: deno test
